spring.application.name=challenge
spring.devtools.restart.enabled=false

# PostgreSQL (dev via Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/challengedb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=challenge
spring.datasource.password=challenge

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Scheduler: 3 horas (igual produção)
scheduler.invoice.rate-ms=10800000

# Stark Bank credentials
stark.project.id=${STARK_PROJECT_ID}
stark.private.key.path=keys/privateKey.pem